### ISSUE TITLE
Error en el registro de ingresos

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/presupuesto_crud#10]
Corregir error en el registro de ingresos.

El error generado es el siguiente:
{
  "Type": "error",
  "Code": "E_22P02",
  "Body": "pq: invalid input syntax for integer: \"\""
}

El endpoint es:
ingresos/CreateIngresos

**Comment by JuanPiedrahita** [comment]
Se aisla el error y se verifica que el error esta en la transacción cuando se registra el ingreso.

**Comment by Soulfilip-UD** [comment]
No se continuara con el Repositorio, se da el Issue por cerrado
