### ISSUE TITLE
Generar Script de Relaciones para Módulo de Presupuesto

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_crud#13]
- [x] Revisar Entidades para el modulo de presupuesto y encontrar relaciones que hacen falta con respecto a las que ya están en el entorno de pruebas

- [x] Generar Script de Relaciones

**Comment by davidmm07** [comment]
se agrega script para agregar las relaciones faltantes https://gist.github.com/davidmm07/c089f54c0560231188055d1eddfaacc5

**Comment by miguelramirez93** [comment]
Se revisa y prueba el script con las migraciones de beego . No se tienen observaciones adicionales.
