### ISSUE TITLE
Revisar código desarrollo Productos

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_crud#3]
Revisar los codigos del api crud, mid y cliente del proceso de productos.

**Comment by davidmm07** [comment]
se añade documento de revisión del desarrollo, con los diferentes endpoints:
https://docs.google.com/document/d/1_ZUSmJf80s6jnM3YEiZXs6u9EgZeiPfSozrM4lZDoxQ/edit?usp=sharing

**Comment by DianaPatriciaRamirez** [comment]
Revisado y aprobado por el lider tecnico @miguelramirez93
