### ISSUE TITLE
Revisión código desarrollo Rubros

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_crud#5]
Revisar los endpoint usados por el componente de rubros del cliente para agregarlos y configurarlos en los  microservicios

**Comment by miguelramirez93** [comment]
Por favor referenciar los commits que se vayan realizando para esta tarea

**Comment by CarlosGutierrezArdila** [comment]
Con respecto a la [documentacion](https://drive.google.com/drive/folders/0B8NdjGOtWwjCU2JlYkFLbVJBUFk) simunistrada por maria claudia, se realizo unicialmente un [analisis](https://docs.google.com/document/d/1qO5YnKRAf5N1ck_D7wdRUKA1FYl_gYbPQLrCDlbk-HY/edit?usp=sharing) de la funcionalidad de los menus que se asignaron inicialmente y su funcionalidad de acuerdo al modelo de negocio, posteriormente se identificaron las [funcionalidades a migrar](https://docs.google.com/document/d/1U9FvsTczPYSz8qSYm-7EMCOtju9LOaex7j2Q5MHP0Gg/edit?usp=sharing) para trabajar en los nuevos apis

**Comment by DianaPatriciaRamirez** [comment]
Revisado y aprobado por el lider tecnico @miguelramirez93
