### ISSUE TITLE
Revisar código desarrollo Fuentes Financiamiento

### ISSUE THREAD

**Issue by mcguegi** [udistrital/presupuesto_crud#6]
Revisar el código de fuentes de financiamiento , identificar los endpoints que se están usando actualmente para los nuevos microservicios.

**Comment by mcguegi** [comment]
Se presenta documento donde se está realizando el respectivo análisis de los endpoints de fuentes
https://docs.google.com/document/d/18geWe6PtV7MXL_MfJUJunj2QDOKBNy-i6_F9JYCxtAY/edit?usp=sharing

**Comment by DianaPatriciaRamirez** [comment]
Revisado por el lider tecnico @miguelramirez93 y aprobado.
